run:permisosArchivo.out
	./permisosArchivo.out
permisosArchivo.out:permisosArchivo.o
	gcc permisosArchivo.o -o permisosArchivo.out
permisosArchivo.o:permisosArchivo.c
	gcc -c -Wall permisosArchivo.c
clear:
	rm permisosArchivo.o permisosArchivo.out
