run:mostar_copiar.out
	./mostar_copiar.out
mostar_copiar.out:mostar_copiar.o
	gcc mostar_copiar.o -o mostar_copiar.out
mostar_copiar.o:mostar_copiar.c
	gcc -c -Wall mostar_copiar.c
clear:
	rm mostar_copiar.o mostar_copiar.out