run:listar_archivos.out
	./listar_archivos.out
listar_archivos.out:listar_archivos.o
	gcc listar_archivos.o -o listar_archivos.out
listar_archivos.o:listar_archivos.c
	gcc -c -Wall listar_archivos.c
clear:
	rm listar_archivos.o listar_archivos.out